export * from "./fill-info-screen"
export * from "./chose-time-screen"
export * from "./select-pos-screen"
export * from "./buy-train-ticket-screen"
export * from "./confirm-transaction-screen"
export * from "./confirm-passenger-info-screen"
export * from "./successfull-screen"
