export const icons = {
  back: require("./arrow-left.png"),
  bullet: require("./bullet.png"),
  scan: require("./icons8PortraitModeScanning.png"),
  linkCard: require("./icons8-mastercard_credit_card.png"),
  rechargeWallet: require("./icons8-wallet_copy_2.png"),
  rechargeMobile: require("./icons8-two_smartphones.png"),
  buyMobileCard: require("./icons8-mobile_payment_copy_2.png"),
  buyGameCard: require("./icons8-nintendo_gamecube_.png"),
  iconFoward: require("./icons8-forward.png"),
  beef: require("./beef.png"),
  checkIn: require("./checkIn.png"),
  promotionImage: require("./promotion-image.png"),
  iconLock: require("./ic_lock.png"),
  iconProfile: require("./profile.png"),
  iconPrivacy: require("./privacy.png"),
  iconAbout: require("./about-this-app.png"),
  iconLanguage: require("./language.png"),
  iconDisplay: require("./display.png"),
  iconSharing: require("./sharing.png"),
  iconTheme: require("./theme.png"),
  iconBank: require("./item-bank.png"),
  iconBankCard: require("./bank-card-image.png"),
  iconBankAccount: require("./icon-bank-account.png"),
  iconAtmCard: require("./icon-atm-card.png"),
  iconMobileNumber: require("./icon-mobile-number.png"),
}

export type IconTypes = keyof typeof icons
