export const icons = {
  back: require("./icons8-back.png"),
  bullet: require("./bullet.png"),
  scan: require("./icons8PortraitModeScanning.png"),
  linkCard: require("./icons8-mastercard_credit_card.png"),
  rechargeWallet: require("./icons8-wallet_copy_2.png"),
  rechargeMobile: require("./icons8-two_smartphones.png"),
  buyMobileCard: require("./icons8-mobile_payment_copy_2.png"),
  buyGameCard: require("./icons8-nintendo_gamecube_.png"),
  iconFoward: require("./icons8-forward.png"),
  beef: require("./beef.png"),
  checkIn: require("./checkIn.png"),
  promotionImage: require("./promotion-image.png"),
  iconLock: require("./ic_lock.png"),
  iconProfile: require("./profile.png"),
  iconPrivacy: require("./privacy.png"),
  iconAbout: require("./about-this-app.png"),
  iconLanguage: require("./language.png"),
  iconDisplay: require("./display.png"),
  iconSharing: require("./sharing.png"),
  iconTheme: require("./theme.png"),
  iconBank: require("./item-bank.png"),
  iconBankCard: require("./bank-card-image.png"),
  iconBankAccount: require("./icon-bank-account.png"),
  iconAtmCard: require("./icon-atm-card.png"),
  iconMobileNumber: require("./icon-mobile-number.png"),
  iconFpt: require("./icon-fpt.jpg"),
  iconWalletTransaction: require("./icon-wallet-transaction.png"),
  train: require("./icons8-train.png"),
  check: require("./icons8-checkmark.png"),
  calendar: require("./icons8-calendar.png"),
  add: require("./icon-add.png"),
  minus: require("./minus.png"),
  seat: require("./seat.png"),
  iconSucces: require("./success.png"),
  iconViettel: require("./icon-viettel.png"),
  iconMobiPhone: require("./icon-mobifone.jpg"),
  iconVinaphone: require("./icon-vinaphone.png"),
  iconVietnammobile: require("./icon-vietnammobile.png"),
  iconDecrement: require("./icon-decrement.png"),
  iconIncrement: require("./icon-add.png"),
  mapDark: require("./mapDark.png"),
  iconLongRightArrow: require("./icons8-long_arrow_right.png"),
  iconClose: require("./cross.png"),
  imageBuyPhoneCardInfo: require("./image-buy-phone-card-info.png"),
}

export type IconTypes = keyof typeof icons
